import { useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CalendarClock, CalendarMinus, Clock3, Search, Sigma, TimerOff } from 'lucide-react'
import ChartCard from '../ChartCard.jsx'
import KpiCard from '../KpiCard.jsx'
import { monthLabel, normalizeText, number, percent } from '../../utils/dashboard.js'
import { additionalRows, buildPermanenceDistribution, buildPermanenceKpis, buildPermanenceMonthly, buildPermanenceSummary, permanenceRange, PERMANENCE_RANGES } from '../../utils/retiros.js'

const dimensions = { plan: 'Plan', asesor: 'Asesor', sede: 'Sede', subuen: 'SubUEN', municipio: 'Municipio', entidad: 'Entidad / convenio' }
const days = (value) => value === null || value === undefined ? 'Sin cálculo' : `${number(Math.round(value))} días`

export default function RetirosPermanence({ rows }) {
  const [type, setType] = useState('TODOS')
  const [range, setRange] = useState('TODOS')
  const [dimension, setDimension] = useState('plan')
  const [selected, setSelected] = useState('')
  const [search, setSearch] = useState('')
  const additions = useMemo(() => additionalRows(rows), [rows])
  const visible = useMemo(() => additions.filter((row) => (type === 'TODOS' || row.codigo_tipo === type) && (range === 'TODOS' || permanenceRange(row)?.key === range)), [additions, type, range])
  const kpis = useMemo(() => buildPermanenceKpis(visible), [visible])
  const distribution = useMemo(() => buildPermanenceDistribution(visible), [visible])
  const monthly = useMemo(() => buildPermanenceMonthly(visible), [visible])
  const summary = useMemo(() => buildPermanenceSummary(visible, dimension), [visible, dimension])
  const active = selected && summary.some((item) => item.name === selected) ? selected : summary[0]?.name || ''
  const detailRows = useMemo(() => visible.filter((row) => !active || (row[dimension] || 'SIN DEFINIR') === active), [visible, dimension, active])
  const types = useMemo(() => buildPermanenceSummary(visible.map((row) => ({ ...row, additional_type: row.codigo_tipo === 'A' ? 'ADICIONAL MAYOR' : 'ADICIONAL MENOR' })), 'additional_type'), [visible])
  const tableRows = summary.filter((item) => normalizeText(item.name).includes(normalizeText(search)))
  const changeDimension = (value) => { setDimension(value); setSelected('') }

  if (!additions.length) return <div className="rounded-3xl border border-amber-200 bg-amber-50 p-8 text-center font-bold text-amber-900">Los filtros actuales no contienen adicionales A o M. Las mascotas P y D no participan en este análisis.</div>
  return <div className="space-y-6">
    <div className="flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4"><select value={type} onChange={(event) => setType(event.target.value)} className="h-10 rounded-xl border border-slate-200 px-3 text-sm font-bold"><option value="TODOS">Todos los adicionales</option><option value="A">Adicional mayor</option><option value="M">Adicional menor</option></select><select value={range} onChange={(event) => setRange(event.target.value)} className="h-10 rounded-xl border border-slate-200 px-3 text-sm font-bold"><option value="TODOS">Todos los rangos</option>{PERMANENCE_RANGES.map((item) => <option key={item.key} value={item.key}>{item.name}</option>)}</select><p className="self-center text-xs font-semibold text-slate-500">Filtros exclusivos de esta vista; nunca incluyen mascotas.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">
      <KpiCard title="Adicionales retirados" value={number(kpis.total)} helper={`${number(kpis.calculable)} con permanencia calculable.`} icon={<Sigma className="size-6" />} accent="rose" />
      <KpiCard title="Permanencia promedio" value={days(kpis.average)} helper="Promedio basado en días válidos." icon={<CalendarClock className="size-6" />} accent="blue" />
      <KpiCard title="Permanencia mediana" value={days(kpis.median)} helper="Menos sensible a valores extremos." icon={<Clock3 className="size-6" />} accent="emerald" />
      <KpiCard title="Antes de 1 mes" value={number(kpis.before1)} helper="Permanencia menor a 30 días." icon={<CalendarMinus className="size-6" />} accent="orange" />
      <KpiCard title="Antes de 6 meses" value={number(kpis.before6)} helper={`${number(kpis.before3)} antes de 3 meses.`} icon={<CalendarMinus className="size-6" />} accent="violet" />
      <KpiCard title="Más de 1 año" value={number(kpis.over1Year)} helper={`${number(kpis.invalid)} sin permanencia calculable.`} icon={<TimerOff className="size-6" />} accent="slate" />
    </div>

    <div className="grid gap-6 xl:grid-cols-2"><ChartCard title="Distribución por permanencia" subtitle="Rangos calculados con días entre ingreso y retiro." accent="rose"><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={distribution}><CartesianGrid stroke="#e2e8f0" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="name" angle={-20} height={72} textAnchor="end" tick={{ fontSize: 9 }} /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="cantidad" name="Adicionales" fill="#be123c" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div></ChartCard><ChartCard title="Adicional mayor vs menor" subtitle="Distribución comparable por los mismos rangos." accent="blue"><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={distribution}><CartesianGrid stroke="#e2e8f0" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="name" angle={-20} height={72} textAnchor="end" tick={{ fontSize: 9 }} /><YAxis allowDecimals={false} /><Tooltip /><Legend /><Bar dataKey="mayor" name="Adicional mayor" fill="#2563eb" /><Bar dataKey="menor" name="Adicional menor" fill="#ea580c" /></BarChart></ResponsiveContainer></div></ChartCard></div>

    <ChartCard title="Evolución mensual de permanencia" subtitle="Promedio, mediana y cantidad según fecha de retiro." accent="violet"><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthly}><CartesianGrid stroke="#e2e8f0" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="key" tickFormatter={(key) => monthLabel(`${key}-01`)} /><YAxis /><Tooltip labelFormatter={(key) => monthLabel(`${key}-01`)} formatter={(value, name) => [name === 'Cantidad' ? number(value) : days(value), name]} /><Legend /><Line type="monotone" dataKey="average" name="Promedio" stroke="#be123c" strokeWidth={3} /><Line type="monotone" dataKey="median" name="Mediana" stroke="#2563eb" strokeWidth={3} /><Line type="monotone" dataKey="total" name="Cantidad" stroke="#0f766e" strokeWidth={2} /></LineChart></ResponsiveContainer></div></ChartCard>

    <div className="grid gap-6 xl:grid-cols-[0.75fr_1.25fr]"><ChartCard title="Resumen por tipo" subtitle="A y M se contabilizan individualmente." accent="orange"><SummaryTable rows={types} first="Tipo de adicional" /></ChartCard><ChartCard title={`Ranking por ${dimensions[dimension]}`} subtitle="Top 12 por cantidad de adicionales retirados." accent="emerald"><div className="mb-3 flex justify-end"><select value={dimension} onChange={(event) => changeDimension(event.target.value)} className="h-9 rounded-lg border border-slate-200 px-3 text-xs font-black">{Object.entries(dimensions).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={summary.slice(0, 12)} layout="vertical"><CartesianGrid stroke="#e2e8f0" strokeDasharray="4 4" horizontal={false} /><XAxis type="number" /><YAxis type="category" dataKey="name" width={160} tick={{ fontSize: 9 }} /><Tooltip /><Bar dataKey="total" name="Adicionales" fill="#0f766e" radius={[0, 8, 8, 0]} onClick={(entry) => setSelected(entry?.name || entry?.payload?.name || '')} /></BarChart></ResponsiveContainer></div></ChartCard></div>
    <DimensionTable rows={tableRows} dimension={dimension} search={search} setSearch={setSearch} selected={active} onSelect={setSelected} />
    <AdditionalDetail rows={detailRows} label={active} />
  </div>
}

function SummaryTable({ rows, first }) { return <div className="overflow-x-auto"><table className="min-w-full whitespace-nowrap text-left text-sm"><thead><tr className="border-b text-[11px] uppercase text-slate-400">{[first, 'Cantidad', 'Promedio', 'Mediana', '< 1 mes', '< 3 meses', '< 6 meses', '> 1 año'].map((head) => <th key={head} className="px-3 py-3">{head}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.name} className="border-b border-slate-100"><td className="px-3 py-3 font-black">{item.name}</td><td className="px-3 py-3">{number(item.total)}</td><td className="px-3 py-3">{days(item.average)}</td><td className="px-3 py-3">{days(item.median)}</td><td className="px-3 py-3">{number(item.before1)}</td><td className="px-3 py-3">{number(item.before3)}</td><td className="px-3 py-3">{number(item.before6)}</td><td className="px-3 py-3">{number(item.over1Year)}</td></tr>)}</tbody></table></div> }
function DimensionTable({ rows, dimension, search, setSearch, selected, onSelect }) { return <ChartCard title="Tabla consolidada de permanencia" subtitle={`${number(rows.length)} categorías bajo los filtros aplicados.`}><label className="relative mb-4 block"><Search className="absolute left-3 top-3 size-4 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Buscar ${dimensions[dimension]}…`} className="h-10 w-full rounded-xl border border-slate-200 pl-9 pr-3 text-sm font-bold" /></label><div className="overflow-x-auto"><table className="min-w-full whitespace-nowrap text-left text-sm"><thead><tr className="border-b text-[11px] uppercase text-slate-400">{[dimensions[dimension], 'Cantidad', 'Promedio', 'Mediana', '< 1 mes', '< 3 meses', '< 6 meses', '> 1 año', '% temprano', 'Sin cálculo'].map((head) => <th key={head} className="px-3 py-3">{head}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.name} onClick={() => onSelect(item.name)} className={`cursor-pointer border-b border-slate-100 hover:bg-rose-50 ${selected === item.name ? 'bg-rose-50' : ''}`}><td className="px-3 py-3 font-black">{item.name}</td><td className="px-3 py-3">{number(item.total)}</td><td className="px-3 py-3">{days(item.average)}</td><td className="px-3 py-3">{days(item.median)}</td><td className="px-3 py-3">{number(item.before1)}</td><td className="px-3 py-3">{number(item.before3)}</td><td className="px-3 py-3">{number(item.before6)}</td><td className="px-3 py-3">{number(item.over1Year)}</td><td className="px-3 py-3">{percent(item.earlyPercentage)}</td><td className="px-3 py-3">{number(item.invalid)}</td></tr>)}</tbody></table></div></ChartCard> }
function AdditionalDetail({ rows, label }) { return <ChartCard title="Detalle de adicionales" subtitle={`${label} · ${number(rows.length)} registros A/M; se muestran hasta 200.`}><div className="overflow-x-auto"><table className="min-w-full whitespace-nowrap text-left text-sm"><thead><tr className="border-b text-[11px] uppercase text-slate-400">{['Contrato', 'Identificación / adicional', 'Tipo', 'Asegurado principal', 'Plan', 'Entidad', 'Asesor', 'Sede / SubUEN', 'Ingreso', 'Retiro', 'Permanencia', 'Rango', 'Vigencia', 'Estado', 'Causal'].map((head) => <th key={head} className="px-3 py-3">{head}</th>)}</tr></thead><tbody>{rows.slice(0, 200).map((row) => <tr key={row.id} className="border-b border-slate-100"><td className="px-3 py-3 font-black">{row.contrato}</td><td className="px-3 py-3"><p className="font-bold">{row.nombre}</p><p className="text-xs text-slate-500">{row.documento}</p></td><td className="px-3 py-3">{row.tipo_retiro}</td><td className="px-3 py-3">{row.asegurado_principal}</td><td className="px-3 py-3">{row.plan}</td><td className="px-3 py-3">{row.entidad}</td><td className="px-3 py-3">{row.asesor}</td><td className="px-3 py-3"><p>{row.sede}</p><p className="text-xs text-slate-500">{row.subuen}</p></td><td className="px-3 py-3">{String(row.fecha_ingreso || '').slice(0, 10) || '—'}</td><td className="px-3 py-3">{row.fecha || '—'}</td><td className="px-3 py-3 font-black">{days(row.dias_permanencia)}</td><td className="px-3 py-3">{permanenceRange(row)?.name}</td><td className="px-3 py-3">{number(row.meses_vigencia)} meses</td><td className="px-3 py-3">{row.estado_contrato}</td><td className="px-3 py-3">{row.causal_retiro}</td></tr>)}</tbody></table></div></ChartCard> }
