import { useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CalendarClock, PawPrint, Search, Sigma, Tag, UsersRound } from 'lucide-react'
import ChartCard from '../ChartCard.jsx'
import KpiCard from '../KpiCard.jsx'
import { DataIllustration, RankingList } from './ExecutiveViz.jsx'
import { monthLabel, normalizeText, number, percent } from '../../utils/dashboard.js'
import { buildPetKpis, buildPetMonthly, buildPetPermanenceDistribution, buildPetSummary, permanenceRange, PERMANENCE_RANGES, petRows } from '../../utils/retiros.js'

const dimensions = { plan: 'Plan', asesor: 'Asesor', sede: 'Sede', subuen: 'SubUEN', municipio: 'Municipio', nombre_entidad: 'Entidad / convenio' }
const days = (value) => value === null || value === undefined ? 'Sin cálculo' : `${number(Math.round(value))} días`

export default function RetirosPets({ rows }) {
  const [type, setType] = useState('TODOS')
  const [range, setRange] = useState('TODOS')
  const [dimension, setDimension] = useState('plan')
  const [selected, setSelected] = useState('')
  const [search, setSearch] = useState('')
  const universe = useMemo(() => petRows(rows), [rows])
  const visible = useMemo(() => universe.filter((row) => (type === 'TODOS' || row.codigo_tipo === type) && (range === 'TODOS' || permanenceRange(row)?.key === range)), [universe, type, range])
  const kpis = useMemo(() => buildPetKpis(visible, rows), [visible, rows])
  const monthly = useMemo(() => buildPetMonthly(visible), [visible])
  const permanence = useMemo(() => buildPetPermanenceDistribution(visible), [visible])
  const summary = useMemo(() => buildPetSummary(visible, dimension), [visible, dimension])
  const types = useMemo(() => buildPetSummary(visible.map((row) => ({ ...row, pet_type: row.codigo_tipo === 'P' ? 'MASCOTA' : 'MASCOTA ADICIONAL' })), 'pet_type'), [visible])
  const active = selected && summary.some((item) => item.name === selected) ? selected : summary[0]?.name || ''
  const details = useMemo(() => visible.filter((row) => !active || (row[dimension] || 'SIN DEFINIR') === active), [visible, dimension, active])
  const tableRows = summary.filter((item) => normalizeText(item.name).includes(normalizeText(search)))
  const peak = [...monthly].sort((a, b) => b.total - a.total)[0]
  const changeDimension = (value) => { setDimension(value); setSelected('') }

  if (!universe.length) return <div className="rounded-3xl border border-violet-200 bg-violet-50 p-8 text-center font-bold text-violet-900">Los filtros actuales no contienen retiros P o D. Los adicionales A y M no participan en esta vista.</div>
  return <div className="space-y-6">
    <div className="flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4"><select value={type} onChange={(event) => setType(event.target.value)} className="h-10 rounded-xl border border-slate-200 px-3 text-sm font-bold"><option value="TODOS">Todas las mascotas</option><option value="P">Mascota</option><option value="D">Mascota adicional</option></select><select value={range} onChange={(event) => setRange(event.target.value)} className="h-10 rounded-xl border border-slate-200 px-3 text-sm font-bold"><option value="TODOS">Todos los rangos</option>{PERMANENCE_RANGES.map((item) => <option key={item.key} value={item.key}>{item.name}</option>)}</select></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
      <KpiCard title="Mascotas retiradas" value={number(kpis.total)} helper={`${percent(kpis.participation)} del total de retiros filtrados.`} icon={<PawPrint className="size-6" />} accent="violet" illustration={<DataIllustration type="pets" />} />
      <KpiCard title="Mascotas tipo P" value={number(kpis.pet)} helper="Registros clasificados como mascota." icon={<Tag className="size-6" />} accent="blue" />
      <KpiCard title="Mascotas adicionales D" value={number(kpis.additionalPet)} helper="Registros clasificados como mascota adicional." icon={<Tag className="size-6" />} accent="orange" />
      <KpiCard title="Contratos relacionados" value={number(kpis.contracts)} helper="Contratos únicos con retiros de mascotas." icon={<UsersRound className="size-6" />} accent="emerald" />
      <KpiCard title="Permanencia promedio" value={days(kpis.average)} helper={`Mediana ${days(kpis.median)} · ${number(kpis.invalid)} sin cálculo.`} icon={<CalendarClock className="size-6" />} accent="rose" />
    </div>

    <div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-950"><strong>Causal de mascota:</strong> SAP no expone una causal individual para P/D. La novedad del contrato no se presenta como causal de la mascota. Los nombres registrados y la especie —perro o gato— sí están disponibles; no existe raza validada.</div>

    <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><ChartCard title="Evolución de retiros de mascotas" subtitle={peak ? `Mayor volumen: ${monthLabel(`${peak.key}-01`)} con ${number(peak.total)} retiros.` : 'Sin periodos.'} accent="violet"><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthly}><CartesianGrid stroke="#e2e8f0" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="key" tickFormatter={(key) => monthLabel(`${key}-01`)} /><YAxis allowDecimals={false} /><Tooltip labelFormatter={(key) => monthLabel(`${key}-01`)} /><Legend /><Line type="monotone" dataKey="mascota" name="Mascota" stroke="#2563eb" strokeWidth={2} /><Line type="monotone" dataKey="mascotaAdicional" name="Mascota adicional" stroke="#7c3aed" strokeWidth={2} /><Line type="monotone" dataKey="total" name="Total" stroke="#be123c" strokeWidth={3} /></LineChart></ResponsiveContainer></div></ChartCard><ChartCard title="Composición de mascotas" subtitle="Cantidad y participación por clasificación P/D." accent="blue"><TypeTable rows={types} /></ChartCard></div>

    <div className="grid gap-6 xl:grid-cols-2"><ChartCard title="Distribución por permanencia" subtitle={`Promedio ${days(kpis.average)} · ${number(kpis.before1)} antes de 1 mes · ${number(kpis.before6)} antes de 6 meses · ${number(kpis.over1Year)} después de 1 año.`} accent="orange"><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={permanence}><CartesianGrid stroke="#e2e8f0" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="name" angle={-20} height={72} textAnchor="end" tick={{ fontSize: 9 }} /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="cantidad" name="Mascotas" fill="#ea580c" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div></ChartCard><ChartCard title={`Ranking por ${dimensions[dimension]}`} subtitle="Top 12 por cantidad de mascotas retiradas." accent="emerald"><div className="mb-3 flex justify-end"><select value={dimension} onChange={(event) => changeDimension(event.target.value)} className="h-9 rounded-lg border border-slate-200 px-3 text-xs font-black">{Object.entries(dimensions).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><RankingList data={summary.slice(0, 12)} valueKey="total" onSelect={(item) => setSelected(item.name)} selected={active} color="#0f766e" /></ChartCard></div>
    <PetTable rows={tableRows} dimension={dimension} search={search} setSearch={setSearch} selected={active} onSelect={setSelected} />
    <PetDetail rows={details} label={active} />
  </div>
}

function TypeTable({ rows }) { return <div className="overflow-x-auto"><table className="min-w-full whitespace-nowrap text-left text-sm"><thead><tr className="border-b text-[11px] uppercase text-slate-400">{['Tipo', 'Total', '% participación', 'Promedio', 'Plan principal', 'Sede principal', 'Asesor principal'].map((head) => <th key={head} className="px-3 py-3">{head}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.name} className="border-b border-slate-100"><td className="px-3 py-3 font-black">{item.name}</td><td className="px-3 py-3">{number(item.total)}</td><td className="px-3 py-3">{percent(item.porcentaje)}</td><td className="px-3 py-3">{days(item.average)}</td><td className="px-3 py-3">{item.principalPlan}</td><td className="px-3 py-3">{item.principalSede}</td><td className="px-3 py-3">{item.principalAsesor}</td></tr>)}</tbody></table></div> }
function PetTable({ rows, dimension, search, setSearch, selected, onSelect }) { return <ChartCard title="Tabla consolidada de mascotas" subtitle={`${number(rows.length)} categorías bajo los filtros aplicados.`}><label className="relative mb-4 block"><Search className="absolute left-3 top-3 size-4 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Buscar ${dimensions[dimension]}…`} className="h-10 w-full rounded-xl border border-slate-200 pl-9 pr-3 text-sm font-bold" /></label><div className="overflow-x-auto"><table className="min-w-full whitespace-nowrap text-left text-sm"><thead><tr className="border-b text-[11px] uppercase text-slate-400">{[dimensions[dimension], 'Total', 'Mascota', 'Mascota adicional', '% participación', 'Permanencia promedio', 'Plan principal', 'Sede principal', 'Asesor principal'].map((head) => <th key={head} className="px-3 py-3">{head}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.name} onClick={() => onSelect(item.name)} className={`cursor-pointer border-b border-slate-100 hover:bg-violet-50 ${selected === item.name ? 'bg-violet-50' : ''}`}><td className="px-3 py-3 font-black">{item.name}</td><td className="px-3 py-3">{number(item.total)}</td><td className="px-3 py-3">{number(item.mascota)}</td><td className="px-3 py-3">{number(item.mascotaAdicional)}</td><td className="px-3 py-3">{percent(item.porcentaje)}</td><td className="px-3 py-3">{days(item.average)}</td><td className="px-3 py-3">{item.principalPlan}</td><td className="px-3 py-3">{item.principalSede}</td><td className="px-3 py-3">{item.principalAsesor}</td></tr>)}</tbody></table></div></ChartCard> }
function PetDetail({ rows, label }) { return <ChartCard title="Detalle de mascotas retiradas" subtitle={`${label} · ${number(rows.length)} registros P/D; se muestran hasta 200.`}><div className="overflow-x-auto"><table className="min-w-full whitespace-nowrap text-left text-sm"><thead><tr className="border-b text-[11px] uppercase text-slate-400">{['Contrato', 'Identificación / nombre', 'Clasificación', 'Especie', 'Asegurado principal', 'Plan', 'Entidad / convenio', 'Asesor', 'Sede / SubUEN', 'Ingreso', 'Retiro', 'Permanencia', 'Estado'].map((head) => <th key={head} className="px-3 py-3">{head}</th>)}</tr></thead><tbody>{rows.slice(0, 200).map((row) => <tr key={row.id} className="border-b border-slate-100"><td className="px-3 py-3 font-black">{row.contrato}</td><td className="px-3 py-3"><p className="font-bold">{row.nombre}</p><p className="text-xs text-slate-500">{row.documento}</p></td><td className="px-3 py-3">{row.tipo_retiro}</td><td className="px-3 py-3">{row.especie_mascota}</td><td className="px-3 py-3">{row.asegurado_principal}</td><td className="px-3 py-3">{row.plan}</td><td className="px-3 py-3"><p>{row.nombre_entidad}</p><p className="text-xs text-slate-500">N.º {row.numero_convenio || '—'}</p></td><td className="px-3 py-3">{row.asesor}</td><td className="px-3 py-3"><p>{row.sede}</p><p className="text-xs text-slate-500">{row.subuen} · {row.municipio}</p></td><td className="px-3 py-3">{String(row.fecha_ingreso || '').slice(0, 10) || '—'}</td><td className="px-3 py-3">{row.fecha || '—'}</td><td className="px-3 py-3 font-black">{days(row.dias_permanencia)}</td><td className="px-3 py-3">{row.estado_contrato}</td></tr>)}</tbody></table></div></ChartCard> }
